Update conversable_agent.py
When using `gpt-3.5-turbo-1106` i got the error bellow

```console
User_Proxy (to chat_manager):

Find a latest paper about gpt-4 on arxiv and find its potential applications in software

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
Traceback (most recent call last):
  File "/home/marcos_souza/Projects/auto-gen/2/./main.py", line 46, in <module>
    user_proxy.initiate_chat(
  File "/home/marcos_souza/.local/lib/python3.10/site-packages/flaml/autogen/agentchat/conversable_agent.py", line 521, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/home/marcos_souza/.local/lib/python3.10/site-packages/flaml/autogen/agentchat/conversable_agent.py", line 324, in send
    recipient.receive(message, self, request_reply, silent)
  File "/home/marcos_souza/.local/lib/python3.10/site-packages/flaml/autogen/agentchat/conversable_agent.py", line 452, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "/home/marcos_souza/.local/lib/python3.10/site-packages/flaml/autogen/agentchat/conversable_agent.py", line 767, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/home/marcos_souza/.local/lib/python3.10/site-packages/flaml/autogen/agentchat/groupchat.py", line 118, in run_chat
    reply = speaker.generate_reply(sender=self)
  File "/home/marcos_souza/.local/lib/python3.10/site-packages/flaml/autogen/agentchat/conversable_agent.py", line 767, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/home/marcos_souza/.local/lib/python3.10/site-packages/flaml/autogen/agentchat/conversable_agent.py", line 635, in generate_code_execution_reply
    return True, f"exitcode: {exitcode} ({exitcode2str})\nCode output: {logs}"
UnboundLocalError: local variable 'exitcode' referenced before assignment
```

This happens because the `logs`, `exitcode` and `exitcode2str` does not have an "initial value", so, when we not have messages no code is executed and the `exitcode`, `logs` and `exitcode2str` is not initiated, so, the code breaks as we can see above.